name: Deploy Frontend Microservice
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/frontend/**'
      - 'lib/frontend-stack.ts'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Node.js (for CDK)
       uses: actions/setup-node@v4
       with:
          node-version: "20"

    
     - name: Install CDK and Deploy
       run: |
         npm install
         npx cdk deploy frontendStack --require-approval never
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

    