name: Seed DynamoDB Manual

on:
  workflow_dispatch:
    # Optional: Add inputs if you want to specify a table name at runtime
    inputs:
      target_table:
        description: 'DynamoDB Table Name'
        required: true
        default: 'YourDefaultTableName'

jobs:
  seed:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install boto3
        run: pip install boto3

      - name: Run Seed Script
        # Passing the table name from the manual input to the script
        run: python src/seed/seed.py ${{ github.event.inputs.target_table }}
